runtime: python39 
entrypoint: gunicorn -b :$PORT main:app  
handlers:
- url: /.*
  script: auto
env_variables:
  # GOOGLE_APPLICATION_CREDENTIALS: "C:/Users/temir/cap5930-project-1-e0c45772710c.json" # edit the path for the credentials
  GOOGLE_CLOUD_PROJECT: "cap5930-project-1"